/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Personality = IDL.Variant({
  'calm' : IDL.Null,
  'playful' : IDL.Null,
  'encouraging' : IDL.Null,
  'witty' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'xp' : IDL.Nat,
  'personality' : Personality,
  'username' : IDL.Text,
  'messagesSent' : IDL.Nat,
  'badges' : IDL.Vec(IDL.Text),
  'streakDays' : IDL.Nat,
  'level' : IDL.Nat,
  'burnoutScore' : IDL.Nat,
  'lastActive' : IDL.Int,
  'completedTopics' : IDL.Vec(IDL.Text),
  'companionName' : IDL.Text,
});
export const Message = IDL.Record({
  'role' : IDL.Text,
  'text' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Question = IDL.Record({
  'topic' : IDL.Text,
  'correctIndex' : IDL.Nat,
  'xpReward' : IDL.Nat,
  'answers' : IDL.Vec(IDL.Text),
  'difficulty' : IDL.Nat,
  'text' : IDL.Text,
});

export const idlService = IDL.Service({
  'addMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addSampleQuestions' : IDL.Func([], [], []),
  'awardBadge' : IDL.Func([IDL.Text], [], []),
  'completeTopic' : IDL.Func([IDL.Text], [], []),
  'getAllStats' : IDL.Func([], [UserProfile], ['query']),
  'getHistory' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getOrCreateProfile' : IDL.Func([IDL.Text], [UserProfile], []),
  'getQuestionsByTopic' : IDL.Func([IDL.Text], [IDL.Vec(Question)], ['query']),
  'updateCompanion' : IDL.Func([IDL.Text, Personality], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Personality = IDL.Variant({
    'calm' : IDL.Null,
    'playful' : IDL.Null,
    'encouraging' : IDL.Null,
    'witty' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'xp' : IDL.Nat,
    'personality' : Personality,
    'username' : IDL.Text,
    'messagesSent' : IDL.Nat,
    'badges' : IDL.Vec(IDL.Text),
    'streakDays' : IDL.Nat,
    'level' : IDL.Nat,
    'burnoutScore' : IDL.Nat,
    'lastActive' : IDL.Int,
    'completedTopics' : IDL.Vec(IDL.Text),
    'companionName' : IDL.Text,
  });
  const Message = IDL.Record({
    'role' : IDL.Text,
    'text' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Question = IDL.Record({
    'topic' : IDL.Text,
    'correctIndex' : IDL.Nat,
    'xpReward' : IDL.Nat,
    'answers' : IDL.Vec(IDL.Text),
    'difficulty' : IDL.Nat,
    'text' : IDL.Text,
  });
  
  return IDL.Service({
    'addMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addSampleQuestions' : IDL.Func([], [], []),
    'awardBadge' : IDL.Func([IDL.Text], [], []),
    'completeTopic' : IDL.Func([IDL.Text], [], []),
    'getAllStats' : IDL.Func([], [UserProfile], ['query']),
    'getHistory' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getOrCreateProfile' : IDL.Func([IDL.Text], [UserProfile], []),
    'getQuestionsByTopic' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'updateCompanion' : IDL.Func([IDL.Text, Personality], [], []),
  });
};

export const init = ({ IDL }) => { return []; };