/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Message {
  'role' : string,
  'text' : string,
  'timestamp' : bigint,
}
export type Personality = { 'calm' : null } |
  { 'playful' : null } |
  { 'encouraging' : null } |
  { 'witty' : null };
export interface Question {
  'topic' : string,
  'correctIndex' : bigint,
  'xpReward' : bigint,
  'answers' : Array<string>,
  'difficulty' : bigint,
  'text' : string,
}
export interface UserProfile {
  'xp' : bigint,
  'personality' : Personality,
  'username' : string,
  'messagesSent' : bigint,
  'badges' : Array<string>,
  'streakDays' : bigint,
  'level' : bigint,
  'burnoutScore' : bigint,
  'lastActive' : bigint,
  'completedTopics' : Array<string>,
  'companionName' : string,
}
export interface _SERVICE {
  'addMessage' : ActorMethod<[string, string], undefined>,
  'addSampleQuestions' : ActorMethod<[], undefined>,
  'awardBadge' : ActorMethod<[string], undefined>,
  'completeTopic' : ActorMethod<[string], undefined>,
  'getAllStats' : ActorMethod<[], UserProfile>,
  'getHistory' : ActorMethod<[], Array<Message>>,
  'getOrCreateProfile' : ActorMethod<[string], UserProfile>,
  'getQuestionsByTopic' : ActorMethod<[string], Array<Question>>,
  'updateCompanion' : ActorMethod<[string, Personality], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];